export const OSDRM_PROCESS_EVENT = {
  DA_CREATED: 'DA_CREATED',
  BC_UPLOADED: 'BC_UPLOADED',
  PV_UPLOADED: 'PV_UPLOADED',
  QR_UPLOADED: 'QR_UPLOADED',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  DPA_CREATED: 'DPA_CREATED',
} as const;
