export const NOTIFICATION_MAIL_QUEUE = 'notification-mail';
export const SEND_MAIL_JOB = 'send-mail';

export const OSDRM_PROCESS_EVENT = {
  // Auth
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  USER_REGISTERED: 'USER_REGISTERED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  USER_UPDATED: 'USER_UPDATED',

  // Demande d'achat (DA)
  DA_CREATED: 'DA_CREATED',
  DA_UPDATED: 'DA_UPDATED',
  DA_DELETED: 'DA_DELETED',
  DA_PUBLISHED: 'DA_PUBLISHED',
  DA_SUBMITTED: 'DA_SUBMITTED',
  DA_REPUBLISHED: 'DA_REPUBLISHED',
  DA_ITEM_ADDED: 'DA_ITEM_ADDED',
  DA_VALIDATED: 'DA_VALIDATED',
  DA_REJECTED: 'DA_REJECTED',
  DA_CHANGE_REQUESTED: 'DA_CHANGE_REQUESTED',

  // Quotation request (QR)
  QR_CREATED: 'QR_CREATED',
  QR_BULK_CREATED: 'QR_BULK_CREATED',
  QR_SUBMITTED: 'QR_SUBMITTED',
  QR_VALIDATED: 'QR_VALIDATED',
  QR_UPLOADED: 'QR_UPLOADED',
  QR_DEROGATION: 'QR_DEROGATION',
  QR_DELETED: 'QR_DELETED',

  // Bon de commande (BC)
  BC_UPLOADED: 'BC_UPLOADED',
  BC_ATTACHED: 'BC_ATTACHED',
  BC_DELETED: 'BC_DELETED',
  BC_VALIDATED: 'BC_VALIDATED',

  // Procès verbal (PV)
  PV_UPLOADED: 'PV_UPLOADED',
  PV_UPDATED: 'PV_UPDATED',
  PV_ITEMS_UPDATED: 'PV_ITEMS_UPDATED',
  PV_ITEMS_SELECTED: 'PV_ITEMS_SELECTED',

  // DAP
  DAP_CREATED: 'DAP_CREATED',

  // Steps & signatures
  STEP_DOCUMENT_UPLOADED: 'STEP_DOCUMENT_UPLOADED',
  STEP_SUBMITTED: 'STEP_SUBMITTED',
  DOCUMENT_SIGNED: 'DOCUMENT_SIGNED',

  // Attachments
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  ATTACHMENT_DELETED: 'ATTACHMENT_DELETED',

  // Derogation
  DEROGATION_VALIDATED: 'DEROGATION_VALIDATED',

  // Satisfaction
  SATISFACTION_SUBMITTED: 'SATISFACTION_SUBMITTED',

  // Suppliers
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED: 'SUPPLIER_UPDATED',
  SUPPLIER_STATUS_UPDATED: 'SUPPLIER_STATUS_UPDATED',

  // Files
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_DELETED: 'FILE_DELETED',

  // Signatures
  SIGNATURE_UPLOADED: 'SIGNATURE_UPLOADED',
  SIGNATURE_ACTIVATED: 'SIGNATURE_ACTIVATED',
  SIGNATURE_DELETED: 'SIGNATURE_DELETED',

  // Budget
  BUDGET_UPLOADED: 'BUDGET_UPLOADED',
  BUDGET_ACTIVATED: 'BUDGET_ACTIVATED',

  // Commentaires
  PURCHASE_COMMENT_ADDED: 'PURCHASE_COMMENT_ADDED',
} as const;

export type OsdrmProcessEvent =
  (typeof OSDRM_PROCESS_EVENT)[keyof typeof OSDRM_PROCESS_EVENT];
